#! /bin/bash

ACTION="custompart-teamviewer_apparmor"

# Add apparmor profile to trust Zoom in Firefox
logger -it "$ACTION" "Adding Teamviewer to firefox apparmor profile"
echo "$( get custom_partition.mountpoint )/teamviewer/usr/bin/teamviewer," > /etc/apparmor.d/abstractions/ubuntu-browsers.d/zoom
echo '#include <abstractions/ubuntu-browsers.d/teamviewer>' >> /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

# reload apparmor only if it is enabled
if [ "$( get system.security.apparmor )" = "true" ] ; then
  logger -it "$ACTION" "Reloading apparmor profiles"
  systemctl reload apparmor.service
else
  logger -it "$ACTION" "Apparmor profiles disabled by setup"
fi

exit 0
